src/main/java/com/scipub/model/User.java
package com.scipub.model;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.Set;
import java.util.UUID;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinTable;
import javax.persistence.Lob;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.Type;

@Entity
@Table(name="users")
public class User extends BaseTimedEntity implements Serializable {

    private static final long serialVersionUID = 978398160453380686L;

    @Id
    @Type(type="uuid-char")
    private UUID id;

    @Column(unique = true)
    private String email;

    @Column
    private String orcid;

    @Column
    private String firstName;

    @Column
    private String middleName;

    @Column
    private String lastName;

    @Column
    private String degree;

    @ManyToOne
    private Organization organization;

    @Column
    private String smallPhotoUri;
    
    @Column
    private String largePhotoUri;

    @Lob
    private String bio;

    @Column
    private String arxivUsername;

    @Column
    private String arxivPassword;

    /**
     * Login token is used for secure cookie-based login
     */
    @Column
    private String loginToken;

    /**
     * Login series is used for secure cookie-based login
     */
    @Column
    private String loginSeries;

    private LocalDateTime lastLoginTime;

    @Column(nullable = false)
    private boolean loginAutomatically;

    @ManyToMany(fetch = FetchType.EAGER)
    @JoinTable(name = "user_branches")
    private Set<Branch> branches = new HashSet<>();

    // deliberately no "gender" - it's irrelevant
    
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getOrcid() {
        return orcid;
    }

    public void setOrcid(String orcid) {
        this.orcid = orcid;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getMiddleName() {
        return middleName;
    }

    public void setMiddleName(String middleName) {
        this.middleName = middleName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getDegree() {
        return degree;
    }

    public void setDegree(String degree) {
        this.degree = degree;
    }

    public Organization getOrganization() {
        return organization;
    }

    public void setOrganization(Organization organization) {
        this.organization = organization;
    }

    public String getSmallPhotoUri() {
        return smallPhotoUri;
    }

    public void setSmallPhotoUri(String smallPhotoUri) {
        this.smallPhotoUri = smallPhotoUri;
    }

    public String getLargePhotoUri() {
        return largePhotoUri;
    }

    public void setLargePhotoUri(String largePhotoUri) {
        this.largePhotoUri = largePhotoUri;
    }

    public String getBio() {
        return bio;
    }

    public void setBio(String bio) {
        this.bio = bio;
    }

    public UUID getId() {
        return id;
    }

    public void setId(UUID userId) {
        this.id = userId;
    }

    public String getArxivUsername() {
        return arxivUsername;
    }

    public void setArxivUsername(String arxivUsername) {
        this.arxivUsername = arxivUsername;
    }

    public String getArxivPassword() {
        return arxivPassword;
    }

    public void setArxivPassword(String arxivPassword) {
        this.arxivPassword = arxivPassword;
    }

    public String getLoginToken() {
        return loginToken;
    }

    public void setLoginToken(String loginToken) {
        this.loginToken = loginToken;
    }

    public String getLoginSeries() {
        return loginSeries;
    }

    public void setLoginSeries(String loginSeries) {
        this.loginSeries = loginSeries;
    }

    public LocalDateTime getLastLoginTime() {
        return lastLoginTime;
    }

    public void setLastLoginTime(LocalDateTime lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }

    public boolean isLoginAutomatically() {
        return loginAutomatically;
    }

    public void setLoginAutomatically(boolean loginAutomatically) {
        this.loginAutomatically = loginAutomatically;
    }

    public Set<Branch> getBranches() {
        return branches;
    }

    public void setBranches(Set<Branch> branches) {
        this.branches = branches;
    }

    public String getDisplayName() {
        return firstName + " " + lastName;
    }
    
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = prime * result + ((id == null) ? 0 : id.hashCode());
        return result;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj)
            return true;
        if (obj == null)
            return false;
        if (getClass() != obj.getClass())
            return false;
        User other = (User) obj;
        if (id == null) {
            if (other.id != null)
                return false;
        } else if (!id.equals(other.id))
            return false;
        return true;
    }

    @Override
    public String toString() {
        return "User [id=" + id + ", email=" + email + ", orcid=" + orcid + ", firstName=" + firstName
                + ", middleName=" + middleName + ", lastName=" + lastName + ", degree=" + degree + ", organization="
                + organization + ", smallPhotoUri=" + smallPhotoUri + ", largePhotoUri=" + largePhotoUri + ", bio="
                + bio + ", arxivUsername=" + arxivUsername + ", arxivPassword=" + arxivPassword + ", loginToken="
                + loginToken + ", loginSeries=" + loginSeries + ", lastLoginTime=" + lastLoginTime
                + ", loginAutomatically=" + loginAutomatically + ", branches=" + branches + "]";
    }
    
}

src/main/java/com/scipub/web/PublicationController.java
package com.scipub.web;

import java.io.IOException;
import java.util.List;

import javax.annotation.PostConstruct;
import javax.inject.Inject;
import javax.servlet.http.HttpSession;

import org.apache.commons.lang3.tuple.ImmutablePair;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.multipart.MultipartFile;

import com.google.common.io.Files;
import com.scipub.dto.PublicationSubmissionDto;
import com.scipub.model.Language;
import com.scipub.model.Publication;
import com.scipub.model.PublicationStatus;
import com.scipub.service.PeerReviewService;
import com.scipub.service.PublicationService;
import com.scipub.tools.BranchJsonGenerator;
import com.scipub.util.FormatConverter;
import com.scipub.util.FormatConverter.Format;
import com.scipub.web.util.Constants;

@Controller
@RequestMapping("/publication")
public class PublicationController {

    static final String PUBLICATION_KEY = "publication";
    static final String OWN_PRELIMINARY_REVIEW_KEY = "ownPreliminaryReview";
    static final String OWN_PEER_REVIEW_KEY = "ownPeerReview";
    static final String PEER_REVIEWS_KEY = "peerReviews";
    static final String PRELIMINARY_REVIEWS_KEY = "preliminaryReviews";

    private static final Logger logger = LoggerFactory.getLogger(PublicationController.class);
    
    private static final String LAST_UPLOADED_FILE_KEY = "lastUploadedFile";
    
    @Inject
    private PublicationService publicationService;
   
    @Inject
    private PeerReviewService peerReviewService;
    
    @Inject
    private UserContext userContext;
    
    private String branchesJson; 
    
    @PostConstruct
    public void init() throws Exception {
        branchesJson = BranchJsonGenerator.getBranchJson(false).replace("'", "\\'");
    }
    @RequestMapping("/new")
    public String newPublication(HttpSession session) {
        // cleanup any previously uploaded file
        session.removeAttribute(LAST_UPLOADED_FILE_KEY);
        return "newPublication";
    }
    
    @RequestMapping("/submit")
    public String submit(PublicationSubmissionDto dto, HttpSession session) {
        fillFileDetails(dto, session);
        String uri = submitPublication(dto);
        return "redirect:/publication?uri=" + uri;
    }
    
    String submitPublication(PublicationSubmissionDto dto) {
        dto.setStatus(PublicationStatus.PUBLISHED);
        String uri = publicationService.submitPublication(dto, userContext.getUser().getId());
        return uri;
    }
    
    @RequestMapping("/saveDraft")
    @ResponseBody
    public String saveDraft(PublicationSubmissionDto dto, HttpSession session) {
        fillFileDetails(dto, session);
        return submitDraft(dto);
    }
    
    String submitDraft(PublicationSubmissionDto dto) {
        dto.setStatus(PublicationStatus.DRAFT);
        return publicationService.submitPublication(dto, userContext.getUser().getId());        
    }
    
    @RequestMapping(value={"", "/"}, params="uri")
    public String getPublication(@RequestParam String uri, Model model) {
        Publication publication = publicationService.getPublication(uri);
        if (publication != null) {
            // if it's a draft and the current user is not an author, don't show
            if (publication.getStatus() == PublicationStatus.DRAFT && !publication.getAuthors().contains(userContext.getUser())) {
                return Constants.REDIRECT_HOME;
            }
            model.addAttribute(PUBLICATION_KEY, publication);
            
            // get peer reviews submitted by the current user
            peerReviewService.getPeerReview(userContext.getUser().getId(), uri)
                .ifPresent(pr -> model.addAttribute(OWN_PEER_REVIEW_KEY, pr));
            peerReviewService.getPreliminaryReview(userContext.getUser().getId(), uri)
                .ifPresent(acceptable -> model.addAttribute(OWN_PRELIMINARY_REVIEW_KEY, acceptable));
            
            // get all peer reviews for this publication
            model.addAttribute(PRELIMINARY_REVIEWS_KEY, peerReviewService.getPreliminaryReviews(uri));
            model.addAttribute(PEER_REVIEWS_KEY, peerReviewService.getPeerReviews(uri));
            return "publication";
        } else {
            return Constants.REDIRECT_HOME;
        }
    }
    
    private void fillFileDetails(PublicationSubmissionDto dto, HttpSession session) {
        @SuppressWarnings("unchecked")
        ImmutablePair<String, byte[]> file = (ImmutablePair<String, byte[]>) session.getAttribute(LAST_UPLOADED_FILE_KEY);
        if (file != null) {
            dto.setOriginalFilename(file.getKey());
            dto.setOriginalFileContent(file.getValue());
        }
    }
    
    @RequestMapping("/uploadFile")
    @ResponseBody
    public void uploadFile(@RequestParam MultipartFile file, HttpSession session) throws IOException {
        session.setAttribute(LAST_UPLOADED_FILE_KEY, new ImmutablePair<String, byte[]>(file.getOriginalFilename(), file.getBytes()));
    }
    
    @RequestMapping("/importFile")
    @ResponseBody
    public UploadResult importFile(@RequestParam MultipartFile file, HttpSession session) throws IOException {
        String extension = Files.getFileExtension(file.getOriginalFilename());
        logger.info("Received file " + file.getOriginalFilename() + " of type " + file.getContentType() + " and size "
                + file.getSize() + " and ext " + extension);
        byte[] md = FormatConverter.convert(Format.forExtension(extension), Format.MARKDOWN, file.getBytes());
        UploadResult result = new UploadResult();
        result.setContent(new String(md, "UTF-8"));
        
        session.setAttribute(LAST_UPLOADED_FILE_KEY, new ImmutablePair<String, byte[]>(file.getOriginalFilename(), file.getBytes()));
        
        return result;
    }
    
    @RequestMapping("/autocomplete")
    public List<PublicationSubmissionDto> autocomplete(@RequestParam String input) {
        return publicationService.findPublication(input);
    }
    
    
    @ModelAttribute("scienceBranchesJson")
    public String getScienceBranchesJson() {
        return branchesJson;
    }
    
    @ModelAttribute("languages")
    public Language[] getLanguages(){
        return Language.values();
    }
    
    public static final class UploadResult {
        private String content;

        public String getContent() {
            return content;
        }

        public void setContent(String content) {
            this.content = content;
        }
    }
}

src/main/webapp/WEB-INF/jsp/branches.jsp
<%@page contentType="text/html" pageEncoding="UTF-8"%>

   <link rel="stylesheet" href="${staticRoot}/css/jquery.tree.min.css">
   <script src="${staticRoot}/js/jquery.tree.min.js"></script>
   
   <script type="text/javascript">
       var branchListFullyVisible = true; 
       
       $(document).ready(function() {
           var json = '${scienceBranchesJson}';
           var branches = $.parseJSON(json);
           var container = $("#branches");
           var elements = [];
           appendBranch(elements, branches);
           container.append(elements.join(""));
           container.tree({
               onCheck: { 
                   ancestors: 'nothing', 
                   descendants: 'nothing' 
               }, 
               onUncheck: { 
                   ancestors: 'nothing' 
               }
           })
           
           
           $("#branchSearchBox").keyup(function() {
               delay(function() {
                   $("#branches li").removeClass("found show collapseChildren");
                   var text = $("#branchSearchBox").val().toLowerCase();

                   // only start filtering after the 2nd character
                   if (text.length < 3) {
                       text = "";
                   }
                   // avoid duplicate traversals if the list is already visible
                   if (!text && branchListFullyVisible) {
                       return;
                   }
                   var ops = 0;
                   $(".branchName").each(function() {
                       var branch = $(this);
                       if (branch.text().toLowerCase().indexOf(text) <= -1) {
                           branch.parent().hide(); // hide the li
                       } else {
                           var currentLi = branch.parent();
                           currentLi.addClass("found");
                           if (!currentLi.hasClass("leaf")) {
                               // collapse all children, so that they are accessible
                               currentLi.addClass("collapseChildren");
                               currentLi.find("li").each(function() {
                                   $(this).addClass("show");
                               });
                           }
                           // (if the input is empty, all nodes will be shown anyway)
                           if (text) {
                               // also show all parents of the li to the top
                               while (currentLi.parent().parent().prop("tagName").toLowerCase() != "div") {
                                   currentLi = currentLi.parent().parent();
                                   if (!currentLi.hasClass("found")) {
                                       currentLi.addClass("found");
                                       currentLi.removeClass("collapseChildren");
                                   } else {
                                       break;
                                   }
                               }
                           }
                       }
                   });
                   
                   // now expand all visible ones
                   $("#branches .show").each(function() {
                       $(this).show();
                   });
                   $("#branches .found").each(function() {
                       var currentLi = $(this);
                       currentLi.show();
                       if (currentLi.parent().parent().prop("tagName").toLowerCase() != "div") {
                           container.tree("expand", currentLi.parent().parent());
                       }
                       if (currentLi.hasClass("collapseChildren")) {
                           container.tree("collapse", currentLi);
                       }
                   });
                   if (!text) {
                       branchListFullyVisible = true;
                   } else {
                       branchListFullyVisible = false;
                   }
               }, 700);
           });
       });

       function appendBranch(container, branches) {
           container.push("<ul>");
           for (var i = 0; i < branches.length; i ++) {
               var branch = branches[i]; 
               var cssClass ="collapsed";
               if (branch.children.length == 0) {
                   cssClass = "leaf";
               }
               container.push('<li class="' + cssClass + '" id="scienceBranchLi' + branch.id +'"><input type="checkbox" name="scienceBranch" id="scienceBranch' + branch.id + 
                   '" value="' + branch.id + '" /><label for="scienceBranch' + branch.id + '" class="branchName">' + branch.name + '</label>');

               if (branches.length > 0) {
                   appendBranch(container, branch.children);
               }
               container.push("</li>");
               
           }
           container.push("</ul>");
       }
       
       var delay = (function(){
         var timer = 0;
         return function(callback, ms){
           clearTimeout (timer);
           timer = setTimeout(callback, ms);
         };
       })();
   </script>
</head>
<input type="text" class="ui-input ui-widget form-control" id="branchSearchBox" style="width: 650px;" placeholder="Search..." />
<div id="branches" style="height: 310px; width: 650px; overflow: auto;">
</div>

src/main/webapp/WEB-INF/jsp/editor.jsp
<%@page contentType="text/html" pageEncoding="UTF-8"%>

<c:if test="${includeResources}">
	<script src="//cdnjs.cloudflare.com/ajax/libs/pagedown/1.0/Markdown.Converter.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/pagedown/1.0/Markdown.Editor.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/pagedown/1.0/Markdown.Sanitizer.js"></script>
	
	<link rel="stylesheet" href="${staticRoot}/css/editor.css" />
</c:if>

<div class="wmd-panel">
	<div id="wmd-button-bar${editorSuffix}"></div>
	<textarea class="form-control wmd-input ${editorClass}" id="wmd-input${editorSuffix}"></textarea>
</div>
<div id="wmd-preview${editorSuffix}" class="wmd-panel wmd-preview"></div>

<br />

<script>
    var converter = new Markdown.getSanitizingConverter();
    var editor = new Markdown.Editor(converter, "${editorSuffix}");
    editor.run();
</script>

src/main/webapp/WEB-INF/jsp/includes.jsp
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>

src/main/webapp/WEB-INF/jsp/newPublication.jsp
<%@page contentType="text/html" pageEncoding="UTF-8"%>
<%@ include file="includes.jsp"%>
<%@taglib prefix="t" tagdir="/WEB-INF/tags"%>

<c:set var="currentPage" value="home" scope="request" />
<t:template>
    <jsp:attribute name="header">
        <script type="text/javascript" src="${staticRoot}/js/jquery.fcbkcomplete.min.js"></script>
        <link href="${staticRoot}/css/autocomplete.css" rel="stylesheet" />
        
        <script src="${staticRoot}/js/jquery.iframe.transport.js"></script>
        <script src="${staticRoot}/js/jquery.fileupload.js"></script>
        
        <script type="text/javascript">
	        $(function () {
			    $('#fileimport').fileupload({
			        dataType: 'json',
			        done: function (e, data) {
		                $("#wmd-input2").val(data.result.content);
			        }
			    });
			});
			
            $(document).ready(function() {
                $("#authors").fcbkcomplete({
                    json_url: "${root}/users/autocompleteList",
                    cache: false,
                    height: 10,
                    filter_case: false,
                    filter_hide: true,
                    newel: true,
                    addontab: true,
                    addoncomma: true,
                    addonblur: true,
                    maxitems: 5,
                    bricket: false,
                    width: "auto"
                });
                $("#authors").trigger("addItem", {title:'${userContext.user.displayName}, ${userContext.user.degree}', value: 'id:${userContext.user.id}'});
                
                //$("#followUpToInternal").autocomplete();
                $("input[name='followUpType']").change(function() {
                    var selected = $('input[name=followUpType]:checked').val();
                    if (selected == "internal") {
                        $("#followUpToInternal").show();
                        $("#followUpToLink,#followUpToDoi").hide();
                    } else if (selected == "link") {
                        $("#followUpToLink").show();
                        $("#followUpToInternal,#followUpToDoi").hide();
                    } else if (selected == "doi") {
                        $("#followUpToDoi").show();
                        $("#followUpToLink,#followUpToInternal").hide();
                    } else {
                    	$("#followUpToLink,#followUpToInternal,#followUpToDoi").hide();
                    }
                    
                });
                
                $("input[name='contentInputType']").change(function() {
                    var selected = $('input[name=contentInputType]:checked').val();
                    if (selected == "direct") {
                        $("#contentEditor,#fileImport").show();
                        $("#externalContent,#fileUpload").hide();
                    } else if (selected == "link") {
                        $("#externalContent").show();
                        $("#contentEditor,#fileImport,#fileUpload").hide();
                    } else if (selected == "upload") {
                        $("#fileUpload").show();
                        $("#contentEditor,#fileImport,#externalContent").hide();
                    }
                });
                
                 $(document).ready(function () {
			        // Save draft every 30 seconds
			        window.setInterval(saveDraft, 30000);
		          });
			
			      function saveDraft() {
			         fillAuthors();
			         fillContent();
			         var params = $("#submissionForm").serialize();
			         $.post("${root}/publication/saveDraft", params)
			         //TODO parse response and set a publicationUri hidden
			      }
            });
            
            function fillAuthors() {
            	var authors = $("#authors :selected");
                var idDelim = "";
                var nameDelim = "";
                var authorIds = "";
                var nonRegisteredAuthors = "";
                authors.each(function(idx, elem) {
                	var value = $(elem).val();
                	if (value.indexOf("id:") === 0) {
                		authorIds += idDelim + value.replace("id:", "");
                        idDelim = ",";
                	} else {
                		nonRegisteredUsers += nameDelim + value;
                        nameDelim = ",";
                	}
                });
                $("#authorIds").val(authorIds);
                $("#nonRegisteredAuthors").val(nonRegisteredAuthors);
            }
            
            function fillContent() {
            	$("#publicationAbstract").val($("#wmd-input1").val());
            	$("#content").val($("#wmd-input2").val());
            }
            
            function handlePrimaryBranchOptions() {
                $("#submissionForm input[name='scienceBranch']").change(function(){
                    var input = $(this);
                    if (input.prop("checked")) {
                        $("#primaryBranch").append($("<option></option>")
                                .attr("value", input.val())
                                .text(input.parent().children("label").text()));
                    } else {
                        $("#primaryBranch").children("option[value='" + input.val() + "']").remove();
                    }
                });
            } 
        </script>
    </jsp:attribute>

    <jsp:body>
        <h1 class="page_head">Publication</h1>
        
        <form role="form" id="submissionForm" class="post-form" 
            style="width: 400px;" onsubmit="fillAuthors();" action="${root}/publication/submit" method="POST">
            <div class="form-group">
                <label for="title">Title</label>
                <input type="text" name="title" id="title" />
            </div>
        
        
            <div class="form-group" id="abstractEditor">
		        <c:set var="editorSuffix" value="1" />
		        <c:set var="includeResources" value="true" />
		        <label>Abstract</label>
		        <%@include file="editor.jsp" %>
		        <input type="hidden" id="publicationAbstract" name="publicationAbstract" />
	        </div>
	        
	         <div class="form-group">
                <label>Content input type</label>

                <div class="radio">
                    <input type="radio" id="contentInputTypeDirect" name="contentInputType" value="direct" checked>
                    <label for="contentInputTypeDirect">Direct input</label>
                </div>
                
                <div class="radio">
                    <input type="radio" id="contentInputTypeUpload" name="contentInputType" value="upload">
                    <label for="contentInputTypeUpload">Upload</label>
                </div>
                
                <div class="radio">
                    <input type="radio" id="contentInputTypeLink" name="contentInputType" value="link">
                    <label for="contentInputTypeLink">External Link</label>
                </div>
            </div>
            
            <div id="fileImport">
                <label for="fileimport">You can import content from a file:</label>
                <input id="fileimport" type="file" name="file" data-url="${root}/publication/importFile"><br />
            </div>
            
	        <div class="form-group" id="contentEditor">
		        <c:set var="editorSuffix" value="2" />
		        <c:set var="includeResources" value="false" />
		        <label>Content</label>
		        <%@include file="editor.jsp" %>
		        <input type="hidden" id="content" name="content" />
	        </div>
	        
            <div class="form-group" id="externalContent" style="display: none;">
                <label>Link to external content</label>
                <input type="text" name="contentLink" placeholder="http://" />
            </div>
            
            <div id="fileUpload" style="display: none;">
                <label for="fileupload">Select file to upload</label>
                <input id="fileupload" type="file" name="fileUpload" data-url="${root}/publication/uploadFile"><br />
            </div>
	        
	        <div class="form-group">
	            <label>Classification</label>
		        <jsp:include page="branches.jsp" />
		        <script type="text/javascript">
		          $(document).ready(function() {
		              // this snippet is here, because if it's put in the header, the branches are not yet loaded
		              handlePrimaryBranchOptions();
		          });
		        </script>
	        </div>
	       
	        <div class="form-group">
               <label for="primaryBranch">Primary branch</label>
               <select id="primaryBranch" name="primaryBranch"></select>
            </div>
            
            <div class="checkbox"> 
               <div class="checkbox">
	               <input type="checkbox" id="pushToArxiv" /><label for="pushToArxiv">Push to arxiv</label>
               </div>
	        </div>
	
            <div class="form-group">
                <label for="language">Language</label>
		        <select name="language" id="language">
		            <c:forEach items="${languages}" var="lang">
		                <option value="${lang.code}">${lang.name}</option>
		            </c:forEach>
		        </select> 
	        </div>
	        
	        <div class="form-group">
				<label for="authors">Authors</label>
				<input type="text" name="authors" id="authors" />
				<input type="hidden" name="authorIds" id="authorIds" value="${userContext.user.id}" />
                <input type="hidden" name="nonRegisteredAuthors" id="nonRegisteredAuthors" />
	        </div>
	        
	        <div class="form-group">
                <label>This publication is a follow-up to:</label>

                <div class="radio">
                    <input type="radio" id="followUpTypeNone" name="followUpType" value="" checked>
                    <label for="followUpTypeNone">Not a follow-up</label><br />
                </div>
                                
                <div class="radio">
	                <input type="radio" id="followUpTypeInternal" name="followUpType" value="internal">
	                <label for="followUpTypeInternal">Scienation publication</label>
                </div>
                
                <div class="radio">
	                <input type="radio" id="followUpTypeLink" name="followUpType" value="link">
	                <label for="followUpTypeLink">External publication (link)</label><br />
	            </div>
	            
	            <div class="radio">
	                <input type="radio" id="followUpTypeDoi" name="followUpType" value="doi">
	                <label for="followUpTypeDoi">External publication (DOI)</label><br />
                </div>
                	                
                <input type="text" id="followUpToInternal" name="followUpToInternal" style="display: none;" />
                <input type="hidden" id="followUpTo" name="followUpTo" />
                <input type="text" id="followUpToLink" name="followUpToLink" style="display: none;"  placeholder="http://" />
                <input type="text" id="followUpToDoi" name="followUpToDoi" style="display: none;" />
            </div>
            
            <div class="form-group">
                <input type="submit" value="Submit" onclick="fillAuthors(); fillContent();">
            </div>
            
	        - send invites to non registered editors
        </form>
    </jsp:body>
</t:template>